### ISSUE TITLE
graphHistQQ

### ISSUE THREAD

**Issue by nishagove** [julipetal/petalNet#4]
graphHistQQ <- function(dataMatrix, fileName="Data_Hist-QQ")
    
For the above function, I believe a prefixed file need to be constructed in the current directory at which the work is performed.
The file should be of a csv, txt or this is just a folder to store the tiff files?What is the format required to built-in  fileName="Data_Hist-QQ"?
In your paper;petal: Co-expression network modellingin R, it states the histogram are found in a MyDataFile.txt. So I created a MyDataFile.txt. and treated it as Data_Hist-QQ. R cannot read a blank txt. file. It says no lines available in input.My question is how to create a fileName="Data_Hist-QQ"?

**Comment by julipetal** [comment]
I am sorry I am not sure I understand. 
graphHistQQ takes a matrix as its input, a regular matrix object in R
graphHistQQfromFile is expecting a file name, this file should be a tab-separated .txt file, just like the sample file; yes the file should be in the same directory as the R console. 

If you post your code and error I will be able to trouble shoot better.

**Comment by nishagove** [comment]
I manage to generate both a histogram and a QQ-plot in a single png. It was actually really easy.
>graphHistQQfromFile("countdata.txt", "Data_Hist-QQ")
And png pops in my working directory. 
However, the measures (x-axis) in my histogram is taking up a max value of 1 200 000 when the total number of reads in my data is just about 20 000. How do I change the body(expressions) of the graphHistQQ function to customize my own range?

**Comment by julipetal** [comment]
That was the goal of the library to make this really easy. 

The x-axis represents the value of the reads, so if you see a value of 120000 then at least one of your reads has this value (or is within this last bin). The sum of your y-values should be equal to total number of reads. But please note: 20000 sounds extremely low for the total number of reads, how many genes/transcripts/nodes are you working with? What is the dimension of your dataset?

**Comment by nishagove** [comment]
![data_hist-qq](https://user-images.githubusercontent.com/30074845/28350250-4d1996ec-6c7a-11e7-815f-27d782615564.png);Attached, the funny histogram
I'm working on transcriptomes generated from RNA-seq. The original data has a dimension of 64361 x 17 (64361= m, 17=n). After filtering using edge R and limma, I ended up with 15352. The dimension of my dataset fed into petal was 15352x17. The total number of reads=mxn= sum of values at y-axis?

**Comment by julipetal** [comment]
Your histogram looks pretty standard for RNAseq. Just based on the little I see about your data, I would recommend to normalize and maybe consider to do some more quality control procedures before feeding it into petal. Are you working with time-points or conditions? How many replicates do you have for each? These are things that need to be addressed before starting any analysis procedures.
