### ISSUE TITLE
create_MMo

### ISSUE THREAD

**Issue by nishagove** [julipetal/petalNet#5]
This function code saves the measure matrix in a table format as following;
save(MMo, file=paste("MMo_", metricChoice, ".RData", sep=""))
How is this interpreted if I wish to load the MMo object for viewing.
I have tried (file="MMo_SP.RData") and (file="MMo_metricChoice.RData") 
and Im getting 'No such file'

**Comment by julipetal** [comment]
metricChoice = <enter your association measure>
load(paste("MMo_", metricChoice, ".RData", sep=""))

.RData objects are loaded with the load() function
