### ISSUE TITLE
Error in scan(fileName, sep = "\t", what = "", nlines = 1) :    'file' must be a character string or connection

### ISSUE THREAD

**Issue by smjazayeri** [julipetal/petalNet#7]
Hello Juli,

Starting with the function createSWSFnetFromFile() I received the following message:
**_Error in scan(fileName, sep = "\t", what = "", nlines = 1) :    'file' must be a character string or connection._**
I have used the example data provided by you but I have the same error message.
I would appreciate you if you could check the problem and give me your suggestion to solve it.

Thanks for your kindly attention in advance.

Best regards
Seyed Mehdi Jazayeri

**Comment by julipetal** [comment]
Hi Seyed, 

What does your function call look like?

You should not get an error for the following:
`createSWSFnetFromFile("SampleInputFile1.txt")`

**Comment by smjazayeri** [comment]
Hi Juli,

Thanks for your reply. I restarted R and then ran `createSWSFnetFromFile("SampleInputFile1.txt")`.
It seems that it worked this time but I got the following error messages and **there is no netwrok file output**.

>createSWSFnetFromFile("SampleInputFile1.txt")
[1] "Reading expression matrix"
Read 8 items
Read 9 items
Read 31815 items
[1] "Read expression matrix"
NULL
[1] "Entering MMoExists loop"
[1] "Calculating association measures"
Read 3 items
Read 18739035 items
[1] 0.976
[1] 0.916
[1] 0.853
[1] 0.793
[1] 0.731
[1] 0.669
[1] 0.607
Attaching package: ‘igraph’
The following objects are masked from ‘package:stats’:
    decompose, spectrum
The following object is masked from ‘package:base’:
    union
Read 3535 items
Read 12496225 items
Read 3535 items
Read 12496225 items
Read 3535 items
Read 12496225 items
Read 3535 items
Read 12496225 items
Read 3535 items
Read 12496225 items
Read 3535 items
Read 12496225 items
Read 3535 items
Read 12496225 items
Read 12 items
Read 84 items
Warning messages:
1: running command 'rm MM.txt' had status 127 
2: running command 'rm AdjM*' had status 127 
3: running command 'rm Neigh*' had status 127 
4: running command 'rm ogenes.RData' had status 127 
5: running command 'rm edgeNum.RData' had status 127 
6: running command 'rm smMM*' had status 127 
7: package ‘igraph’ was built under R version 3.4.1 
8: running command 'rm Sym.*' had status 127

The generated files are as follows:

**adjMSP_0.607.RData
adjMSP_0.669.RData
AdjMSP_0.669to0.607.txt
adjMSP_0.731.RData
AdjMSP_0.731to0.669.txt
adjMSP_0.793.RData
AdjMSP_0.793to0.731.txt
adjMSP_0.853.RData
AdjMSP_0.853to0.793.txt
adjMSP_0.916.RData
AdjMSP_0.916to0.853.txt
adjMSP_0.976.RData
AdjMSP_0.976to0.916.txt
AdjMSP_1to0.976.txt
edgeNum.RData
expM.RData
forDA.RData
GeneralInfo.txt
MM.txt
MMo_SP.RData
Neighbors.SP_0.669to0.607.txt
Neighbors.SP_0.731to0.669.txt
Neighbors.SP_0.793to0.731.txt
Neighbors.SP_0.853to0.793.txt
Neighbors.SP_0.916to0.853.txt
Neighbors.SP_0.976to0.916.txt
Neighbors.SP_1to0.976.txt
NetworkStats.txt
numGenes.RData
ogenes.RData
SampleInputFile1.txt
smMM.SP_0.669to0.607.RData
smMM.SP_0.669to0.607.txt
smMM.SP_0.731to0.669.RData
smMM.SP_0.731to0.669.txt
smMM.SP_0.793to0.731.RData
smMM.SP_0.793to0.731.txt
smMM.SP_0.853to0.793.RData
smMM.SP_0.853to0.793.txt
smMM.SP_0.916to0.853.RData
smMM.SP_0.916to0.853.txt
smMM.SP_0.976to0.916.RData
smMM.SP_0.976to0.916.txt
smMM.SP_1to0.976.RData
smMM.SP_1to0.976.txt
Sym.SP.AdjMSP_0.669to0.607.txt
Sym.SP.AdjMSP_0.731to0.669.txt
Sym.SP.AdjMSP_0.793to0.731.txt
Sym.SP.AdjMSP_0.853to0.793.txt
Sym.SP.AdjMSP_0.916to0.853.txt
Sym.SP.AdjMSP_0.976to0.916.txt
Sym.SP.AdjMSP_1to0.976.txt
thresholds.RData
winningThresh.RData**

Your opinion and suggestions are of help.

P.S.: the version of R and packages are

>sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.1.2 petal_0.2.4 

loaded via a namespace (and not attached):
[1] compiler_3.4.0  magrittr_1.5    tools_3.4.0     pkgconfig_2.0.1

**Comment by julipetal** [comment]
The `rm` commands do not work on windows, you should manually delete these files as the take up a lot of memory. 

petal depends on an older version of igraph, the newer version is somewhat slower. Please install the older version of igraph and you will be able to generate VNs.
